# Generated by Django 5.1.2 on 2024-10-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('campus', models.CharField(choices=[('RECREIO', 'campus_recreio'), ('TAQUARA', 'campus_taquara'), ('BARRA_DA_TIJUCA', 'campus_barra_da_tijuca')])),
                ('serie', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('carga_horaria', models.IntegerField()),
                ('professor', models.CharField(max_length=50)),
                ('alunos', models.ManyToManyField(to='notas.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='materias',
            field=models.ManyToManyField(to='notas.materia'),
        ),
    ]
