# Generated by Django 5.1.2 on 2024-10-17 12:14

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='materias',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='alunos',
        ),
        migrations.AddField(
            model_name='aluno',
            name='createdAt',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AddField(
            model_name='aluno',
            name='materiasMatriculadas',
            field=models.ManyToManyField(related_name='alunos', to='notas.materia'),
        ),
        migrations.AddField(
            model_name='materia',
            name='alunosMatriculados',
            field=models.ManyToManyField(related_name='materias', to='notas.aluno'),
        ),
        migrations.AddField(
            model_name='materia',
            name='createdAt',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nome',
            field=models.CharField(choices=[('MATEMATICA', 'matematica'), ('PORTUGUES', 'portugues'), ('HISTORIA', 'historia'), ('GEOGRAFIA', 'geografia'), ('CIENCIAS', 'ciencias'), ('INGLES', 'ingles'), ('EDUCACAO_FISICA', 'educacao_fisica')], max_length=50),
        ),
    ]
