# Generated by Django 5.1.2 on 2024-10-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_remove_aluno_materias_remove_materia_alunos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='statusMatricula',
            field=models.BooleanField(default=True),
        ),
    ]
