# Generated by Django 5.1.2 on 2024-10-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_aluno_statusmatricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='materiasMatriculadas',
            new_name='materias_matriculadas',
        ),
    ]
