# Generated by Django 5.1.2 on 2024-10-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_rename_materiasmatriculadas_aluno_materias_matriculadas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='statusMatricula',
            new_name='status_matricula',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='alunosMatriculados',
            new_name='alunos_matriculados',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
